title: Zahra Rahmani
logo: /assets/img/Zahra_Rahmani.JPG
description: "I'm a masters graduate in Linguistics."
show_downloads: true
skills: "Data Science - User Experience Research - Speech Processing"
theme: jekyll-theme-freelancer-theme
title: Zahra Rahmani
author-img: /assets/img/Zahra_Rahmani.JPG
description: "I'm a masters graduate in Linguistics."
show_downloads: true
skills: "Data Science - User Experience Research - Speech Processing"
theme: jekyll-theme-freelancer-theme

title: Zahra Rahmani
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Zahra Rahmani # add your name
author-img: /assets/img/Zahra_Rahmani.JPG # add your photo
about-author:  I'm a masters graduate in Linguistics.# add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: # add your Github handle
social-linkedin: www.linkedin.com/in/zari-rahmani # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
