title: Zahra Rahmani
theme: jekyll-theme-minimal
email: rahmany.zahra@gmail.com
url: zarirahmani.github.io 
description: "I'm a masters graduate in Linguistics."
skills: "Data Science - User Experience Research - Speech Processing"
meta_author: Zahra Rahmani

