title: Zahra Rahmani
logo: /assets/img/Zahra_Rahmani.JPG
theme: jekyll-theme-minimal
description: "I'm a masters graduate in Linguistics."
show_downloads: true
skills: "Data Science - User Experience Research - Speech Processing"
theme: jekyll-theme-minimal

