title: Zahra Rahmani
remote_theme: jekyll-theme-freelancer-theme
email: rahmany.zahra@gmail.com
url: zarirahmani.github.io 
description: "I'm a masters graduate in Linguistics."
skills: "Data Science - User Experience Research - Speech Processing"
meta_author: Zahra Rahmani

